### ISSUE TITLE
I know this repo is old but... any chance of adding user/password ?

### ISSUE THREAD

**Issue by MopheusDG** [avenantsoftware/XBMCArduino#1]
Hi, I've been using part of your code to control my Kodi but since I needed to add user/password I cannot find any way to make the Authorization work.... this is what I've added:

Client.println("Authorization: Basic XXXXXXXXXXXXXXXXXXXXXXXXX");

Where XXXX is the Base64 encoded user:password, but still doesn't work. Any ideas ??

**Comment by MxAshUp** [comment]
I'm probably zero help because I never got this library working. But here are some ideas:

- Have you checked if Kodi has a setting for adjusting authorization? (ie, turn on Basic Auth)
- Can you pass the username/password through the connection url? For example: http[s]://[username[:password]@]host[:port]/
- Where did you put Client.println(..)? I think it should go after the "Host: XBMC"

**Comment by MopheusDG** [comment]
1) I added web access via HTTP and set a User and Password, not sure how to turn Basic Auth, I think it's the default for http access...?
2) Kodi does no longer work using that http://user:password format, it was deprecated if I'm not wrong.
3) Tried everywhere.... before the Host, after the Host, at the begining.... everywhere :)

No luck....
